### ISSUE TITLE
请教下，task worker需要开启协程吗？

### ISSUE THREAD

**Issue by he426100** [friendsofhyperf/async-task#1]
我看Task里是随机向worker/task worker发任务，如果task _worker不开协程的不就跟worker下环境不一致了么？但是Hyperf文档写着不推荐在task中开启协程，就很疑惑。

**Comment by huangdijia** [comment]
这个不需要开 task 进程

**Comment by he426100** [comment]
如果开了task进程呢？

**Comment by huangdijia** [comment]
没有关系吧
