### ISSUE TITLE
Some tasks getting lost when executing quickly

### ISSUE THREAD

**Issue by binaryfire** [friendsofhyperf/async-task#2]
Hi

I'm using this in my `SendEmailController` to send emails:

```
        AsyncTask::deliver(function() use ($data, $fromName, $fromEmail, $bodyHtml, $bodyText) {
            $this->ses->send(
                fromName: $fromName,
                fromEmail: $fromEmail,
                to: $data['to'],
                subject: $data['subject'],
                bodyHtml: $bodyHtml,
                bodyText: $bodyText
            );
        });
    }

```    
The `ses` service's `send` method sends an email and adds an entry to the `sent_emails` table.

I am testing in Postman and everything works great when I send consecutive requests slowly. But when I send consecutive requests quickly some of the tasks don't execute / get processed. For example, I sent 15 successful requests to my controller in Postman very quickly:

<img width="252" alt="image" src="https://github.com/friendsofhyperf/async-task/assets/5361908/d81cd556-6e9a-4e8a-b4a8-ca76eb7eae4f">

But only 13 emails were sent:
<img width="184" alt="image" src="https://github.com/friendsofhyperf/async-task/assets/5361908/cae1b2a6-4cad-4dab-9211-216192d963f6">

This is confirmed by the logs as well.

**Comment by binaryfire** [comment]
UPDATE: I tested again and discovered that all the tasks are correctly logged as "Processing". I made _**20**_  fast requests and saw 20 of these entries:

`[2023-09-03 xxxxxxxx] Processing Task[Closure@/App/Service/MailerService.php:33]`

But I only see _**16**_ of these log entries:

`[2023-09-03 xxxxxxxx] Processed Task[Closure@/App/Service/MailerService.php:33]`

And also _**16**_ entries in the db log table:
<img width="182" alt="image" src="https://github.com/friendsofhyperf/async-task/assets/5361908/3e1233e8-5eed-4a58-8a12-4d3d31fb4832">

So 4 of the tasks entered the "Processing" state but never completed or failed. They just disappeared. It seems `async-task` is having problems when it is under load

**Comment by huangdijia** [comment]
Try it like：

```php
AsyncTask::deliver(function() use ($data, $fromName, $fromEmail, $bodyHtml, $bodyText) {
    $ses = new Ses();
    $ses->send(
        fromName: $fromName,
        fromEmail: $fromEmail,
        to: $data['to'],
        subject: $data['subject'],
        bodyHtml: $bodyHtml,
        bodyText: $bodyText
    );
});
```

**Comment by binaryfire** [comment]
I tried it this way, unfortunately same problem:

```
use FriendsOfHyperf\AsyncTask\AbstractTask;
use FriendsOfHyperf\AsyncTask\Task;

class SendSesEmailTask extends AbstractTask
{
    public function handle():void
    {
        // Sending logic
    }
}

Task::deliver(new SendSesEmailTask());

```

I've switched to `async-queue` for now
