### ISSUE TITLE
async-task在单核服务器上无效

### ISSUE THREAD

**Issue by he426100** [friendsofhyperf/async-task#3]
async-task本来用的很顺手，直到我把它部署到单核服务器上，才发现它是无效的

**Comment by huangdijia** [comment]
不建议使用这个组件了

**Comment by he426100** [comment]
应该用哪个？

**Comment by huangdijia** [comment]
Coroutined::create() 或者用 async-queue 组件，效果都差不多。

不过单核服务器用协程也没用，CPU 没法切换。

**Comment by he426100** [comment]
明白了;
有一种场景，比如订单成功后请求一个接口，请求接口这个行为或结果不应该影响到处理订单的transaction，它是可以延后一点处理的，用队列稍微重了点，用 Coroutine::create() 能简单的实现这个效果，即使是单核服务器也可以。这种情况，我应该使用队列吗？ async-task 自带重试机制，我感觉还是挺好用的

**Comment by huangdijia** [comment]
可以用队列，比较可靠
